qdrant/vector-db-benchmark

poetry.lock, pyproject.toml, run.py
I added some enhancements to the run script:
- possibility to provide multiple engines/datasets to the script, not just a single pattern 
- a single experiment timeout, so it won't run forever (24h by default)
- possibility to continue if there was an exception thrown during the experiment (by default keeping the old behaviour)
The latter enhancement is useful while running the experiment on multiple datasets. Right now running them requires constant monitoring and manually restarting the benchmark on a different dataset on failure, even though it could be handled automatically.
=> Enhance run.py with timeout and multiple engines/datasets

engine/clients/milvus/configure.py
I tried to launch `milvus` on `random-range-2048-angular-filters` dataset and it failed on the uploading stage with the following traceback:
```
raise DataNotMatchException(message=f"The data type of field {y.name} doesn't match, expected: {y.dtype.name}, got {x.dtype.name}")
AttributeError: 'int' object has no attribute 'name'
```
Once I changed `float` to `double` the errors disappeared and milvus was able to finish successfully.
=> fix: replace float with double

engine/clients/elasticsearch/configure.py, engine/clients/elasticsearch/upload.py, engine/servers/elasticsearch-single-node/docker-compose.yaml
- set refresh_interval to -1 to speed up indexing
https://www.elastic.co/guide/en/elasticsearch/reference/8.7/tune-for-indexing-speed.html#_unset_or_increase_the_refresh_interval
- exclude vector from source
https://www.elastic.co/guide/en/elasticsearch/reference/8.7/tune-for-disk-usage.html#disable-source
=> Elasticsearch - Disable source and refresh

tools/run_ci.sh, tools/run_client_script.sh
Preserve modified time on scp and use it to sort files
=> fix: Preserve modified time on scp and use it to sort files

.github/workflows/manual-benchmark.yaml, tools/upload_results_postgres.sh
Store branch and dataset for benchmarks. 
This will make it easier to visualize the results of manual benchmark workflow across different branches and datasets.
=> feat: Store branch and dataset for benchmarks

engine/clients/elasticsearch/configure.py
Elasticsearch has updated its limit on vector dimensions. We need to upgrade for a fair comparison :)
=> fix: Upgrade elasticsearch dimensions limit

tools/run_benchmarks.sh
Related to https://github.com/qdrant/vector-db-benchmark/commit/8324a57b8da4297f57289aa595f38ee09d70f371
=> feat: Allow using any Qdrant version for single node benchmarks

tools/run_experiment.sh
Shouldn't skip benchmarks on existing results in case of CI benchmarks.
=> fix: CI benchmarks should run even on existing results

engine/clients/qdrant/search.py, engine/clients/qdrant/upload.py
This can be validated by running this config:
```json
{
"name": "qdrant-parallel-error",
"engine": "qdrant",
"connection_params": { "timeout": 30 },
"collection_params": {
"optimizers_config": { "memmap_threshold": 10000000 }
},
"search_params": [
{ "parallel": 16, "search_params": { "hnsw_ef": 128 } },
{ "parallel": 32, "search_params": { "hnsw_ef": 128 } },
{ "parallel": 64, "search_params": { "hnsw_ef": 128 } },
{ "parallel": 100, "search_params": { "hnsw_ef": 128 } }
],
"upload_params": { "parallel": 16, "batch_size": 1024 }
}
```
Previously it used to throw:
```bash
File "/home/user/projects/qdrant/vector-db-benchmark/engine/base_client/client.py", line 113, in run_experiment
search_stats = searcher.search_all(
File "/home/user/projects/qdrant/vector-db-benchmark/engine/base_client/se …
```
=> fix: Reuse of Qdrant process pool should work

experiments/configurations/pgvector-single-node.json
Most of pgvector configs were named as qdrant
=> fix: Use pgvector config properly

.github/workflows/continuous-benchmark.yaml, experiments/configurations/qdrant-vs-weaviate.json
This will help with catching bugs faster. Doing once a day isn't enough, once every hour is better.
=> feat: Increase frequency of CI benchmarks to 1hr

engine/base_client/client.py, engine/base_client/configure.py, engine/clients/client_factory.py, engine/clients/qdrant/configure.py, run.py
I feel like sparse vector support should not be in `__init__`
I tried this naming, it seems to be better for the configurator classes, but worse for the client class, idk, feel free to change it back if you want
=> refactoring: refactor sparse vector support

.pre-commit-config.yaml, engine/base_client/__init__.py, engine/base_client/client.py, engine/base_client/upload.py, engine/base_client/utils.py, engine/clients/elasticsearch/__init__.py, engine/clients/elasticsearch/search.py, engine/clients/elasticsearch/upload.py, engine/clients/milvus/__init__.py, engine/clients/milvus/search.py, engine/clients/milvus/upload.py, engine/clients/opensearch/__init__.py, engine/clients/opensearch/search.py, engine/clients/opensearch/upload.py, engine/clients/pgvector/configure.py, engine/clients/pgvector/search.py, engine/clients/pgvector/upload.py, engine/clients/qdrant/__init__.py, engine/clients/qdrant/search.py, engine/clients/qdrant/upload.py, engine/clients/redis/__init__.py, engine/clients/redis/configure.py, engine/clients/redis/search.py, engine/clients/redis/upload.py, engine/clients/weaviate/__init__.py, engine/clients/weaviate/search.py, engine/clients/weaviate/upload.py, run.py
This PR does two things:
- Use `Query` and `Record` in all the engines. 
- Introduces [Ruff](https://docs.astral.sh/ruff/) linter (written in Rust :crab: ) in precommit hooks to run type checks and help maintain code quality.
Part of sparse vectors CI benchmark PR. https://github.com/qdrant/vector-db-benchmark/pull/114
=> refactor: Update all engines to use Query and Record dataclasses

.github/workflows/continuous-benchmark.yaml, tools/run_ci.sh, tools/setup_ci.sh
We don't need mc anymore. We extract and store the data in Postgres and viz with Grafana
=> fix: Remove mc

.github/workflows/continuous-benchmark.yaml, .github/workflows/manual-benchmark.yaml, dataset_reader/sparse_reader.py
- Add mmap support for reading sparse vectors to avoid OOM error in CI
=> feat: Add mmap support for reading sparse vectors to avoid OOM error in CI

dataset_reader/sparse_reader.py
Fix OOM of sparse vectors benchmarks on CI
=> fix: Avoid reading all mmaped sparse vectors into memory

tools/run_experiment.sh
Otherwise it fails silently and ends up using the old container:
```
Error response from daemon: conflict: unable to remove repository reference "qdrant/vector-db-benchmark:latest" (must force) - container b6bbafc6355b is using its referenced image 24afca33f44f
```
=> feat: Force docker image removal

tools/qdrant_collect_stats.sh, tools/run_ci.sh, tools/run_client_script.sh, tools/upload_results_postgres.sh
This might give us more insights in CI benchmarks
=> feat: Use both RssAnon and VmRSS in CI benchmarks

.github/workflows/continuous-benchmark.yaml, datasets/datasets.json
Reasoning:
- Using a smaller dataset means it will finish faster. 
- This is also important because our crons run every 4 hours and the runs shouldn't overlap because they use the same machine
- All other CI benchmark datasets are of similar size (<1GB)
=> feat: Add DBpedia OpenAI embedding dataset with 100k vectors

.github/workflows/continuous-benchmark.yaml
Important for us to be notified quickly
Took the code from https://github.com/qdrant/crasher/blob/master/.github/workflows/run-crasher.yml (thanks @tellet-q )
=> feat: Add Slack alert for CI benchmarks

.github/workflows/continuous-benchmark.yaml, tools/run_ci.sh
Due to some issues. Some of the datasets are taking forever to index. This also stops other datasets from running because  we schedule a cron every 4hours. So I think it's a good idea that we introduce timeouts of 15m for each run.
This PR also introduces a Slack alert in case the workflow doesn't run as expected (error or timeout)
=> feat: Add 15m timeout for CI benchmarks

tools/run_ci.sh
It's not able to log the error properly
=> fix: Typo in func name

engine/clients/opensearch/search.py
Current filtering query does post-filtering which is not ideal and resulted in low precision.
Results with post filtering:
```
{
"params": {
"dataset": "arxiv-titles-384-angular-filters",
"experiment": "opensearch-default",
"engine": "opensearch",
"parallel": 1,
"config": {
"knn.algo_param.ef_search": 128
}
},
"results": {
"total_time": 708.6168032020068,
"mean_time": 0.07045893384491791,
"mean_precisions": 0.11399200000000001,
"std_time": 0.06840096039381999,
"min_time": 0.008397486002650112,
"max_time": 3.3753458530118223,
"rps": 14.111999538838594,
"p95_time": 0.18164870390755816,
"p99_time": 0.20864198897208555
}
}
```
Results with new efficient filtering:
```
{
"params": {
"dataset": "arxiv-titles-384-angular-filters",
"experiment": "opensearch-default",
"engine": "opensearch", …
```
=> Use efficient filtering for opensearch

datasets/datasets.json, engine/clients/opensearch/parser.py
Also specify schema for id in arxiv-titles-384-angular filters dataset. This is needed as default mapping created by opensearch takes the type as float, but in the dataset we also have string.
This leads to 99% precision on the test dataset with opensearch.
```
{
"params": {
"dataset": "arxiv-titles-384-angular-filters",
"experiment": "opensearch-default",
"engine": "opensearch",
"parallel": 10,
"config": {
"knn.algo_param.ef_search": 128
}
},
"results": {
"total_time": 391.3466711850051,
"mean_time": 0.37053632343088827,
"mean_precisions": 0.98962,
"std_time": 0.3485163122349799,
"min_time": 0.04950378900684882,
"max_time": 3.548553360000369,
"rps": 25.552791773390613,
"p95_time": 1.0473700279486362,
"p99_time": 1.4396829416653787
}
}
```
Fixes #171
=> Fix opensearch query parser

tools/run_experiment.sh, tools/run_server_container.sh
CI benches were failing. I found the following errors from [the logs](https://github.com/qdrant/vector-db-benchmark/actions/runs/10287664428/job/28471248469):
```
Error response from daemon: conflict: unable to remove repository reference "docker.io/qdrant/qdrant:master" (must force) - container 40054a4e5693 is using its referenced image 3d4537be4e7c
Error response from daemon: Conflict. The container name "/qdrant-continuous" is already in use by container "40054a4e5693eda6b6597fc6f247ad365c5be985a7d545e3084c34b994ebac68". You have to remove (or rename) that container to be able to reuse that name.
```
Also, on sshing into the machine I found that sometimes 2 vector-db-benchmark containers are running if the 1st workflow is cancelled. This isn't ideal for perf benchmarking and should be …
=> Allow CI to force clear previously running resources if required

.github/workflows/continuous-benchmark.yaml
Run tenants benchmark in a subsequent job (`runTenantsBenchmark`). Note `runTenantsBenchmark` runs right after the normal `runBenchmark` job regardless of its status.
Example run: https://github.com/qdrant/vector-db-benchmark/actions/runs/10403187016
=> Split Ci benchmarks into 2 jobs

.github/workflows/continuous-benchmark.yaml
Let's see if 160mb limit solves irregular failures of the job.
=> Increase CONTAINER_MEM_LIMIT to 160mb

engine/clients/pgvector/parser.py
Pgvector client does not use proposer parameter in condiction builder for and clauses.
Fixes : https://github.com/qdrant/vector-db-benchmark/issues/194
=> fix: pgvector and_subfilter

.github/workflows/continuous-benchmark.yaml, engine/clients/qdrant/search.py, engine/servers/qdrant-continuous-benchmarks-with-volume/docker-compose.yaml, tools/run_server_container_with_volume.sh
* Add logging to search_one function
* Use default docker volumes
=> Improve volumes and logging

.github/workflows/continuous-benchmark.yaml, engine/base_client/client.py, run.py, tools/run_ci.sh, tools/run_client_script.sh, tools/run_experiment.sh, tools/run_remote_benchmark.sh, tools/run_server_container_with_volume.sh, tools/upload_parallel_results_postgres.sh
* introduce new cli arg `--skip-configure` to `run.py`, that allows for skipping collection re-creation during the upload stage. It is optional, and set to `False` by default, so it has no effect on any other benchmarks.
* add a new experiment mode `parallel`, run upload and search containers at the same time during that experiment
* add a new table to store the new benchmark's results 
**Note**: the benchmark stores search_time in the above table, that corresponds to `results.total_time` (a value measured by python `time.perf_counter()` to calculate time spend on executing all search queries)
=> Add benchmark on parallel upload and search

engine/clients/qdrant/upload.py
The `max_optimization_threads` parameter is currently configured incorrectly after uploading, and this does not allow parallel optimizations.
This PR sets it to a high value so that we do use parallel optimizations as it'll likely result in better results. Note that setting such high limit is fine, because in practice we're still limited by CPU budget. We cannot set it back to `null` through this API.
On my machine with 24 CPUs I now see 3 parallel optimizations, rather than just 1. The indexing time is more than 2 times quicker.
Am I correct that the benchmark machine we used for the public results does not have more than 8 CPU cores? If we did have more cores, we should probably redo the benchmarks.
=> Allow parallel optimizations in Qdrant after uploading

.github/workflows/continuous-benchmark-2.yaml, .github/workflows/continuous-benchmark.yaml
* Introduce concurrency group: `continuous-benchmark`
* Move `runLoadTimeBenchmark` into separate workflow within `continuous-benchmark` 
* Only run `runLoadTimeBenchmark`  once a day at midnight (and at at any time if triggered manually or on repository_dispatch).
**Note**: concurrency group restricts to only running single workflow at a time, any newly triggered run will be marked as `pending`, any existing pending runs will be replaced with a new one.
=> Only run runLoadTimeBenchmark once per day

.github/workflows/manual-compare-versions-benchmark.yaml, poetry.lock, tools/compare_versions/prepare_image.sh, tools/run_ci.sh, tools/upload_parallel_results_postgres.sh, tools/upload_results_postgres.sh
A new workflow to compare 2 qdrant versions in 1 run:
1. check if there are images for the provided versions
2. if there is no image -> trigger image build workflow in qdrant repo and wait for image to appear in remote repo for up to 150 minutes
3. if image is ok -> proceed to benchmark execution
4. in the end compare results between to versions
Note: if the workflow triggered image build in the main repo and that triggered workflow is queued, then there is nothing we can do about it. If the triggered workflow took longer than 150 minutes the original job will fail
=> Complete compare versions' workflow

tools/compare_versions/prepare_image.sh
Cancel workflow during prepare_image.sh execution in case of any error.
=> Cancel manual workflow early

.github/workflows/continuous-benchmark.yaml, Dockerfile, engine/clients/qdrant/search.py, experiments/configurations/qdrant-on-disk.json, experiments/configurations/qdrant-single-node.json, poetry.lock, pyproject.toml, tools/run_experiment.sh
* Introduce an optional input `with_payload` into Continuous Benchmark. If `true` - searcher will add with_payload:True to search requests.
* Update poetry version to 2.1.2 (otherwise docker build failed due to package-mode param not being recognized)
* Update poetry lock
=> Run ci with payload

tools/run_client_script.sh
Fix `argument list too long` error:
https://github.com/qdrant/vector-db-benchmark/actions/runs/14294219494/job/40060489525
=> Use find instead of ls to search files

.github/workflows/manual-benchmark.yaml, .github/workflows/manual-compare-versions-benchmark.yaml
Follow-up on <https://github.com/qdrant/vector-db-benchmark/pull/241>, <https://github.com/qdrant/vector-db-benchmark/pull/243>
We can use a boolean input to show a checkbox, that's probably a bit nicer.
Docs: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onworkflow_callinputsinput_idtype
As far as I understand this still produces 'true' or 'false'
=> Use boolean input type in workflow input for toggling all feature flags

engine/clients/qdrant/configure.py, engine/clients/qdrant/upload.py, experiments/configurations/qdrant-on-disk.json, experiments/configurations/qdrant-single-node.json
Related to https://github.com/qdrant/qdrant/pull/6325, https://github.com/qdrant/qdrant/pull/6355.
~~This PR removes code that disables indexing while uploading. Immediate indexing is now enabled unconditionally (i.e. both for `dev` and `master`), so we can compare how incremental indexing improves the situation.~~
---
This PR changes the logic that disables indexing while uploading, making it configurable.
Old logic:
- **Before uploading**: `max_optimization_threads` = `0`.
I.e. indexing disabled unconditionally.
- **After uploading**: `max_optimization_threads` = `100_000`.
I.e. start indexing using CPU quota unconditionally.
New logic:
- **Before uploading**: `max_optimization_threads` defaults to `0` but could be overwritten in JSON.
- **After uploading**: If …
=> Enable indexing while uploading

.github/workflows/actions/send-slack-msg/action.yaml, .github/workflows/continuous-benchmark-2.yaml, .github/workflows/continuous-benchmark.yaml
Introduce a new gh action to send notification to slack.
=> Reduce ci code duplication

.github/workflows/continuous-benchmark.yaml, .github/workflows/manual-compare-versions-benchmark.yaml, tools/qdrant_collect_cpu_usage.sh, tools/run_ci.sh, tools/run_remote_benchmark.sh, tools/upload_parallel_results_postgres.sh, tools/upload_results_postgres.sh
Accumulate CPU usage stats for `default` (!) benchmark strategy. Currently there are 2 sources:
1. telemetry reports from qdrant 
2. `utime` obtained from server machine (calculated as difference between utime before benchmark and utime after the benchmark, divided by 100 to get number of seconds).
https://docs.rs/procfs/latest/procfs/process/struct.Stat.html#structfield.utime 
Example run: 
https://github.com/qdrant/vector-db-benchmark/actions/runs/14702755957
=> Add CPU stats into monitoring

README.md, run.py
Improve docs and examples in README
=> Improve README docs and examples
