qdrant/vector-db-benchmark

engine/clients/elasticsearch/upload.py, engine/servers/elasticsearch-single-node/docker-compose.yaml
Following general recommendation and fully merge merge to one segment.
https://www.elastic.co/guide/en/elasticsearch/reference/8.7/tune-knn-search.html#_force_merge_to_one_segment
=> Elasticsearch force merge, fully merge to one segment

.github/workflows/continuous-benchmark.yaml, .github/workflows/manual-benchmark.yaml, engine/servers/qdrant-continuous-benchmarks/docker-compose.yaml, tools/run_server_container.sh, tools/upload_results_postgres.sh
Add a manual benchmarking workflow where you can choose which Qdrant branch to use.
=> ci: Add manual benchmarking workflow

tools/remote/setup_benchmark_server.sh
Delete qdrant/qdrant:dev image before using it.
=> feat: Always use latest version of Qdrant dev

scripts/process-benchmarks.ipynb
Prepares benchmark results for https://qdrant.tech/benchmarks/
=> feat: Add jupyter notebook to process benchmark results

datasets/datasets.json
=> feat: Include Yandex T2I GT 100k dataset

engine/servers/qdrant-cluster-mode/docker-compose.yaml
Add docker compose to run benchmarks in cluster mode on a single machine.
=> feat: Docker compose for cluster mode

.github/workflows/manual-benchmark.yaml, tools/run_server_container.sh
Fix checking releases and explain usage
=> fix: Checking any release from tags

tools/run_server_container.sh
Wait for Qdrant build to be completed
=> fix: Natively build qdrant

tools/run_client_script.sh
=> fix: Only scp the latest results and show correct values for dev and master

engine/clients/qdrant/search.py, engine/clients/qdrant/upload.py
Refer to the original issue: #80 
The detail is here: https://github.com/grpc/grpc/blob/master/doc/fork_support.md#current-status
=> Enable grpc fork support

engine/clients/redis/upload.py
=> fix: Typo in upload.py

experiments/configurations/qdrant-vs-weaviate.json, experiments/configurations/weaviate-single-node.json
Make Weaviate config consistent with all the other engines.
=> fix: Inconsistent Weaviate config

scripts/process-benchmarks.ipynb
Should help https://github.com/qdrant/vector-db-benchmark/issues/104#issuecomment-2057970146
=> refactor: Fix and simplify benchmark processing notebook

.github/workflows/continuous-benchmark.yaml, .github/workflows/manual-benchmark.yaml
=> fix: Manual benchmarks

.github/workflows/continuous-benchmark.yaml
The current 1M dataset takes 20-30mins to run.
=> fix: Use smaller sparse dataset for faster iteration

.github/workflows/continuous-benchmark.yaml, tools/run_client_script.sh, tools/run_server_container.sh
This should give us more insights.
=> feat: Add H&M filter dataset to CI benchmarks

.github/workflows/manual-all-engines-benchmark.yaml, engine/servers/weaviate-single-node/docker-compose.yaml
Use github action ([https://github.com/dorny/paths-filter](https://github.com/dorny/paths-filter)) to filter changed files. 
**Note**: all the jobs run, but steps that actually run the tests are skipped according to filters.
=> Fix github triggers

engine/servers/qdrant-cluster-mode/docker-compose.yaml
=> fix: Rename nodes in cluster mode

tools/qdrant_collect_stats.sh, tools/run_ci.sh, tools/run_client_script.sh, tools/run_experiment.sh, tools/run_remote_benchmark.sh, tools/run_server_container.sh
=> feat: Add debug logs

tools/run_client_script.sh
=> fix: Unbound variable error

tools/run_client_script.sh
Memory will be collected later by [qdrant_collect_stats.sh](https://github.com/qdrant/vector-db-benchmark/blob/master/tools/qdrant_collect_stats.sh)
=> Only copy search and upload in first step

tools/run_ci.sh
To ensure that we know when it breaks
=> Fail CI if any benches fail

scripts/process-benchmarks.ipynb
=> docs: update process-benchmarks.ipynb

.github/workflows/continuous-benchmark.yaml, tools/run_ci.sh
=> Report dataset's info in slack

.github/workflows/continuous-benchmark-2.yaml, .github/workflows/continuous-benchmark.yaml, engine/servers/qdrant-continuous-benchmarks/docker-compose.yaml, tools/run_server_container.sh, tools/run_server_container_with_volume.sh
Propagate QDRANT__FEATURE_FLAGS__ALL=true for CI benchmarks running for "dev"
=> Run benchmarks with feature flags for dev

.github/workflows/manual-compare-versions-benchmark.yaml
Example run: https://github.com/qdrant/vector-db-benchmark/actions/runs/14748948096
=> Improve GH outputs
